# Site settings
title: Jwalin Thaker
description: A page overflowing with me. 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jwalin Thaker
user_description: Hi, this is me, the amiable and ambitious neighbourhood nerdy developer.
user_title: Machine Learning  
email: jwalinthaker@gmail.com
twitter_username: https://twitter.com/JwalinT
github_username: https://github.com/Jwalin-Thaker  
linkedin_username: https://www.linkedin.com/in/jwalin-thaker-95b3b7ba/

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
